name: CI

on:
  push:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RUNTIMEE_PAT }}

      - uses: pnpm/action-setup@v4.4.0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - run: pnpm typecheck
      - run: pnpm boundaries
      - run: pnpm lint:eslint
      - run: pnpm test:unit
