name: Release

on:
  push:
    branches: [master]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RUNTIMEE_PAT }}
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.RUNTIMEE_PAT }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: corepack use pnpm@10.33.0
      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm version:packages
          publish: pnpm release
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
